# Outputs for MongoDB Query Translator MLOps Infrastructure

output "cluster_name" {
  description = "EKS cluster name"
  value       = module.eks.cluster_name
}

output "cluster_endpoint" {
  description = "Endpoint for EKS control plane"
  value       = module.eks.cluster_endpoint
}

output "cluster_security_group_id" {
  description = "Security group ids attached to the cluster control plane"
  value       = module.eks.cluster_security_group_id
}

output "cluster_iam_role_name" {
  description = "IAM role name associated with EKS cluster"
  value       = module.eks.cluster_iam_role_name
}

output "cluster_certificate_authority_data" {
  description = "Base64 encoded certificate data required to communicate with the cluster"
  value       = module.eks.cluster_certificate_authority_data
}

output "cluster_primary_security_group_id" {
  description = "The cluster primary security group ID created by EKS on the cluster and other resources"
  value       = module.eks.cluster_primary_security_group_id
}

output "vpc_id" {
  description = "ID of the VPC where the cluster is deployed"
  value       = module.vpc.vpc_id
}

output "vpc_cidr_block" {
  description = "The CIDR block of the VPC"
  value       = module.vpc.vpc_cidr_block
}

output "private_subnets" {
  description = "List of IDs of private subnets"
  value       = module.vpc.private_subnets
}

output "public_subnets" {
  description = "List of IDs of public subnets"
  value       = module.vpc.public_subnets
}

output "mlops_s3_bucket" {
  description = "S3 bucket for MLOps artifacts"
  value       = aws_s3_bucket.mlops_bucket.bucket
}

output "mlops_s3_bucket_arn" {
  description = "S3 bucket ARN for MLOps artifacts"
  value       = aws_s3_bucket.mlops_bucket.arn
}

output "mlflow_db_endpoint" {
  description = "RDS instance endpoint for MLflow database"
  value       = aws_db_instance.mlflow_db.endpoint
}

output "mlflow_db_port" {
  description = "RDS instance port for MLflow database"
  value       = aws_db_instance.mlflow_db.port
}

output "redis_endpoint" {
  description = "ElastiCache Redis endpoint"
  value       = aws_elasticache_replication_group.airflow.configuration_endpoint_address
}

output "redis_port" {
  description = "ElastiCache Redis port"
  value       = aws_elasticache_replication_group.airflow.port
}

output "mongodb_secret_arn" {
  description = "ARN of the MongoDB URI secret"
  value       = aws_secretsmanager_secret.mongodb_uri.arn
}

output "mlops_iam_role_arn" {
  description = "ARN of the MLOps IAM role"
  value       = aws_iam_role.mlops_role.arn
}

# Kubernetes configuration
output "kubectl_config" {
  description = "kubectl config as generated by the module"
  value       = "aws eks update-kubeconfig --region ${var.aws_region} --name ${module.eks.cluster_name}"
}

# Connection information for applications
output "connection_info" {
  description = "Connection information for the MLOps stack"
  value = {
    cluster_name    = module.eks.cluster_name
    cluster_endpoint = module.eks.cluster_endpoint
    s3_bucket       = aws_s3_bucket.mlops_bucket.bucket
    mlflow_db       = aws_db_instance.mlflow_db.endpoint
    redis_endpoint  = aws_elasticache_replication_group.airflow.configuration_endpoint_address
  }
}
